# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 16ysm(云扫码)

on:
  workflow_dispatch:
  schedule:
     - cron: '20 5-16 * * *'
  watch:
    types: started
#env:
  #TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/adw2s/Action.git ~/Scripts
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/Scripts
          npm install -g npm
          npm update

      - name: '运行 【16ysm(云扫码)】'
        if: env.YSMURL
        run: |
          cd ~/Scripts
          node Task/16ysm.js
        env:
          YSMURL: ${{ secrets.YSMURL }}
          YSMHD: ${{ secrets.YSMHD }}
          YSMBODY: ${{ secrets.YSMBODY }}
          YSM2BODY: ${{ secrets.YSM2BODY }}
          YSMTX: ${{ secrets.YSMTX }}
          ysmbd: ${{ secrets.ysmbd }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
